name = "howmanysmall/janitor"
version = "1.17.0"
description = "A garbage collector object implementation for Roblox, featuring support for custom cleanup methods, Promises, and instance linking."
authors = [
	"Validark <Validark@pm.me>",
	"HowManySmall <howmanysmall@gmail.com>",
	"OverHash <>",
	"codesenseAye <>",
]
includes = [
	"pesde.toml",
	"README.md",
	"LICENSE",
	"src/**/*.luau",
	".luaurc",
	"docs/**/*.md",
]
repository = "https://github.com/howmanysmall/Janitor"
license = "MIT"

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/RGFQQ/pesde-index"
pesde = "https://github.com/pesde-pkg/index"
